media:
  input: content/media
  output: media
  extensions: [jpg, svg]
content:
  - name: homepage
    label: Home Page
    type: file
    path: content/index.md
    fields:
      - name: hero
        label: Hero Image
        type: image
        required: true
      - name: body
        label: Body
        type: rich-text
  