media:
  input: content/media
  output: /website/media
  extensions: [jpg, svg]
content:
  - name: site
    label: Site
    type: file
    path: content/site.md
    fields:
      - name: name
        label: Name
        required: true
        type: string
      - name: url
        label: URL
        required: true
        type: string
  - name: homepage
    label: Home Page
    type: file
    path: content/index.md
    fields:
      - name: hero
        label: Hero Image
        type: image
        required: true
      - name: body
        label: Body
        type: rich-text
  - name: pages
    label: Pages
    type: collection
    path: content/pages
    filename: '{primary}.md'
    view: 
      fields: [title, published]
      primary: title
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: published
        label: Published
        type: boolean
        required: true
        default: false
      - name: body
        label: Body
        type: rich-text