media:
  input: content/media
  output: deploy/media
content:
  - name: homepage
    label: Home Page
    type: file
    path: content/index.md
    fields:
      - name: body
        label: Body
        type: rich-text
  